const riddleslist = {
  beginner: [
    { riddle: "What has to be broken before you can use it?", answer: "An egg" },
    { riddle: "I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "A candle" },
    { riddle: "What month of the year has 28 days?", answer: "All of them" },
    { riddle: "What is full of holes but still holds water?", answer: "A sponge" },
    { riddle: "What question can you never answer yes to?", answer: "Are you asleep yet?" },
    { riddle: "What is always in front of you but can’t be seen?", answer: "The future" },
    { riddle: "There’s a one-story house in which everything is yellow. Yellow walls, yellow doors, yellow furniture. What color are the stairs?", answer: "There aren’t any—it’s a one-story house" },
    { riddle: "What can you break, even if you never pick it up or touch it?", answer: "A promise" },
    { riddle: "What goes up but never comes down?", answer: "Your age" },
    { riddle: "A man who was outside in the rain without an umbrella or hat didn’t get a single hair on his head wet. Why?", answer: "He was bald" },
    { riddle: "What gets wet while drying?", answer: "A towel" },
    { riddle: "What can you keep after giving to someone?", answer: "Your word" },
    { riddle: "I shave every day, but my beard stays the same. What am I?", answer: "A barber" },
    { riddle: "You see a boat filled with people, yet there isn’t a single person on board. How is that possible?", answer: "All the people on the boat are married" },
    { riddle: "You walk into a room that contains a match, a kerosene lamp, a candle, and a fireplace. What would you light first?", answer: "The match" },
    { riddle: "A man dies of old age on his 25th birthday. How is this possible?", answer: "He was born on February 29" },
    { riddle: "I have branches, but no fruit, trunk, or leaves. What am I?", answer: "A bank" },
    { riddle: "What can’t talk but will reply when spoken to?", answer: "An echo" },
    { riddle: "The more of this there is, the less you see. What is it?", answer: "Darkness" },
    { riddle: "David’s parents have three sons: Snap, Crackle, and what’s the name of the third son?", answer: "David" },
    { riddle: "I follow you all the time and copy your every move, but you can’t touch me or catch me. What am I?", answer: "Your shadow" },
    { riddle: "What has many keys but can’t open a single lock?", answer: "A piano" },
    { riddle: "What can you hold in your left hand but not in your right?", answer: "Your right elbow" },
    { riddle: "What is black when it’s clean and white when it’s dirty?", answer: "A chalkboard" },
    { riddle: "What gets bigger when more is taken away?", answer: "A hole" },
    { riddle: "I’m light as a feather, yet the strongest person can’t hold me for five minutes. What am I?", answer: "Your breath" },
    { riddle: "I’m found in socks, scarves, and mittens; and often in the paws of playful kittens. What am I?", answer: "Yarn" },
    { riddle: "Where does today come before yesterday?", answer: "The dictionary" },
    { riddle: "What invention lets you look right through a wall?", answer: "A window" },
    { riddle: "If you’ve got me, you want to share me; if you share me, you haven’t kept me. What am I?", answer: "A secret" },
    { riddle: "What can’t be put in a saucepan?", answer: "It’s lid" },
    { riddle: "What goes up and down but doesn’t move?", answer: "A staircase" },
    { riddle: "If you’re running in a race and you pass the person in second place, what place are you in?", answer: "Second place" },
    { riddle: "It belongs to you, but other people use it more than you do. What is it?", answer: "Your name" },
    { riddle: "What has lots of eyes, but can’t see?", answer: "A potato" },
    { riddle: "What has one eye, but can’t see?", answer: "A needle" },
    { riddle: "What has many needles, but doesn’t sew?", answer: "A Christmas tree" },
    { riddle: "What has hands, but can’t clap?", answer: "A clock" },
    { riddle: "What has legs, but doesn’t walk?", answer: "A table" },
    { riddle: "What has one head, one foot, and four legs?", answer: "A bed" },
    { riddle: "What can you catch, but not throw?", answer: "A cold" },
    { riddle: "What kind of band never plays music?", answer: "A rubber band" },
    { riddle: "What has many teeth, but can’t bite?", answer: "A comb" },
    { riddle: "What building has the most stories?", answer: "The library" },
    { riddle: "What tastes better than it smells?", answer: "Your tongue" },
    { riddle: "What has words, but never speaks?", answer: "A book" },
    { riddle: "What has a head and a tail but no body?", answer: "A coin" },
    { riddle: "What kind of coat is always wet when you put it on?", answer: "A coat of paint" },
    { riddle: "What has an eye but cannot see?", answer: "A needle" },
    { riddle: "What gets bigger the more you take away?", answer: "A hole" }
  ]
};