const riddleslist = [
  { riddle: "What has to be broken before you can use it?", answer: "egg" },
  { riddle: "I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "candle" },
  { riddle: "What month of the year has 28 days?", answer: "all of them" },
  { riddle: "What is full of holes but still holds water?", answer: "sponge" },
  { riddle: "What question can you never answer yes to?", answer: "are you asleep yet" },
  { riddle: "What is always in front of you but can’t be seen?", answer: "future" },
  { riddle: "There’s a one-story house where everything inside is yellow. What color are the stairs?", answer: "no stairs" },
  { riddle: "What can you break, even if you never pick it up or touch it?", answer: "promise" },
  { riddle: "What goes up but never comes down?", answer: "age" },
  { riddle: "A man who was outside in the rain without an umbrella didn’t get a single hair on his head wet. Why?", answer: "he was bald" },
  { riddle: "What gets wet while drying?", answer: "towel" },
  { riddle: "What can you keep after giving to someone?", answer: "your word" },
  { riddle: "I shave every day, but my beard stays the same. What am I?", answer: "barber" },
  { riddle: "You see a boat filled with people, but there isn’t a single person on board. How is that possible?", answer: "all married" },
  { riddle: "You walk into a room that contains a match, a kerosene lamp, a candle, and a fireplace. What do you light first?", answer: "match" },
  { riddle: "A man dies of old age on his 25 birthday. How is this possible?", answer: "born on february 29" },
  { riddle: "I have branches, but no fruit, trunk, or leaves. What am I?", answer: "bank" },
  { riddle: "What can’t talk but will reply when spoken to?", answer: "echo" },
  { riddle: "The more of this there is, the less you see. What is it?", answer: "darkness" },
  { riddle: "David’s parents have three sons: Snap, Crackle, and what’s the name of the third son?", answer: "david" },
  { riddle: "What room do ghosts avoid?", answer: "living room" },
  { riddle: "What invention lets you look right through a wall?", answer: "window" },
  { riddle: "If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", answer: "mirror" },
  { riddle: "What goes up and down but doesn’t move?", answer: "staircase" },
  { riddle: "I have hands but no arms and a face but no eyes. What am I?", answer: "clock" },
  { riddle: "What can fill a room but takes up no space?", answer: "light" },
  { riddle: "If you’re running in a race and you pass the person in second place, what place are you in?", answer: "second" },
  { riddle: "Where does today come before yesterday?", answer: "dictionary" },
  { riddle: "What has many keys but can’t open a single lock?", answer: "piano" },
  { riddle: "What can travel all around the world without leaving its corner?", answer: "stamp" },
  { riddle: "What has legs but doesn’t walk?", answer: "table" },
  { riddle: "What kind of band never plays music?", answer: "rubber band" },
  { riddle: "What has words but never speaks?", answer: "book" },
  { riddle: "What runs all around a backyard yet never moves?", answer: "fence" },
  { riddle: "What can you hold in your left hand but not in your right?", answer: "your right elbow" },
  { riddle: "What kind of coat is best put on wet?", answer: "coat of paint" },
  { riddle: "What has one eye but can’t see?", answer: "needle" },
  { riddle: "What has many needles, but doesn’t sew?", answer: "pine tree" },
  { riddle: "What has hands but can’t clap?", answer: "clock" },
  { riddle: "What building has the most stories?", answer: "library" },
  { riddle: "What tastes better than it smells?", answer: "tongue" },
  { riddle: "What kind of tree can you carry in your hand?", answer: "palm" },
  { riddle: "Where does one wall meet the other wall?", answer: "corner" },
  { riddle: "What has a bottom at the top?", answer: "leg" },
  { riddle: "What has four wheels and flies?", answer: "garbage truck" },
  { riddle: "What has an eye but cannot see?", answer: "needle" },
  { riddle: "What has cities, but no houses; forests, but no trees; and water, but no fish?", answer: "map" },
  { riddle: "What is easy to lift but hard to throw?", answer: "feather" },
  { riddle: "What is cut on a table but is never eaten?", answer: "deck of cards" },
  { riddle: "What has a neck but no head?", answer: "bottle" },
  { riddle: "What has one head, one foot, and four legs?", answer: "bed" },
  { riddle: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "letter m" },
  { riddle: "What has a head, a tail, but no body?", answer: "coin" },
  { riddle: "What is always answered without being asked?", answer: "telephone" },
  { riddle: "What has an end but no beginning, a home but no family, a space without room?", answer: "keyboard" },
  { riddle: "The more you take, the more you leave behind. What am I?", answer: "footsteps" },
  { riddle: "What comes down but never goes up?", answer: "rain" },
  { riddle: "What has 13 hearts but no other organs?", answer: "deck of cards" },
  { riddle: "What has an endless supply of letters but starts empty?", answer: "mailbox" },
  { riddle: "You see me once in June, twice in November, but not at all in May. What am I?", answer: "letter e" },
  { riddle: "I am easy to lift but hard to throw. What am I?", answer: "feather" },
  { riddle: "What can you hear but not see or touch, even though you control it?", answer: "voice" },
  { riddle: "I am an odd number. Take away a letter and I become even. What number am I?", answer: "seven" },
  { riddle: "What gets sharper the more you use it?", answer: "brain" },
  { riddle: "What has four fingers and a thumb but is not alive?", answer: "glove" },
  { riddle: "What has a head and a tail but no body?", answer: "coin" },
  { riddle: "If two’s company, and three’s a crowd, what are four and five?", answer: "nine" },
  { riddle: "What word is spelled incorrectly in every dictionary?", answer: "incorrectly" },
  { riddle: "What begins with an E but only has one letter?", answer: "envelope" },
  { riddle: "What begins and ends with an E but only contains one letter?", answer: "envelope" },
  { riddle: "What goes through cities and fields but never moves?", answer: "road" },
  { riddle: "The more you take, the more you leave behind. What are they?", answer: "footsteps" },
  { riddle: "What starts with T, ends with T, and has T in it?", answer: "teapot" },
  { riddle: "What has many teeth but cannot bite?", answer: "comb" },
  { riddle: "What comes at night without being called and is lost in the day without being stolen?", answer: "stars" },
  { riddle: "What has a head, a tail, is brown, and has no legs?", answer: "penny" },
  { riddle: "What flattens all mountains, wipes out all species, destroy every building, and turns everything into pieces?", answer: "time" },
  { riddle: "What belongs to you, but other people use it more than you do?", answer: "your name" },
  { riddle: "What can fill a room but takes up no space?", answer: "light" },
  { riddle: "The more you take, the more you leave behind. What am I?", answer: "footsteps" },
  { riddle: "What has no life but can die?", answer: "battery" },
  { riddle: "What has no beginning, middle or end?", answer: "circle" },
  { riddle: "I have keys but no locks. I have space but no room. You can enter, but you can’t go outside. What am I?", answer: "keyboard" },
  { riddle: "What gets bigger when more is taken away?", answer: "hole" },
  { riddle: "What can't be put in a saucepan?", answer: "its lid" },
  { riddle: "The more you take away from me, the bigger I get. What am I?", answer: "hole" },
  { riddle: "What can't talk but will reply when spoken to?", answer: "echo" },
  { riddle: "What kind of band never plays music?", answer: "rubber band" },
  { riddle: "What has one eye but can’t see?", answer: "needle" },
  { riddle: "What has an eye but can't see?", answer: "needle" },
  { riddle: "What goes all around the world but stays in a corner?", answer: "stamp" },
];